/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "primary-fixed": "#eaddff",
              "on-error": "#690005",
              "on-primary-fixed": "#25005a",
              "tertiary-container": "#a15100",
              "surface": "#051424",
              "on-surface-variant": "#ccc3d8",
              "on-primary-container": "#ede0ff",
              "inverse-surface": "#d4e4fa",
              "tertiary": "#ffb784",
              "on-tertiary-container": "#ffe0cd",
              "surface-dim": "#051424",
              "tertiary-fixed": "#ffdcc6",
              "surface-container-lowest": "#010f1f",
              "on-secondary-container": "#aeb9d0",
              "surface-container-highest": "#273647",
              "on-secondary": "#263143",
              "on-primary": "#3f008e",
              "on-tertiary": "#4f2500",
              "surface-tint": "#d2bbff",
              "on-tertiary-fixed": "#301400",
              "tertiary-fixed-dim": "#ffb784",
              "inverse-on-surface": "#233143",
              "surface-container": "#122131",
              "primary": "#d2bbff",
              "outline-variant": "#4a4455",
              "on-error-container": "#ffdad6",
              "primary-container": "#7c3aed",
              "surface-bright": "#2c3a4c",
              "error-container": "#93000a",
              "secondary": "#bcc7de",
              "error": "#ffb4ab",
              "on-primary-fixed-variant": "#5a00c6",
              "primary-fixed-dim": "#d2bbff",
              "on-tertiary-fixed-variant": "#713700",
              "outline": "#958da1",
              "secondary-fixed": "#d8e3fb",
              "secondary-fixed-dim": "#bcc7de",
              "on-secondary-fixed-variant": "#3c475a",
              "secondary-container": "#3e495d",
              "on-background": "#d4e4fa",
              "surface-container-low": "#0d1c2d",
              "inverse-primary": "#732ee4",
              "background": "#051424",
              "surface-container-high": "#1c2b3c",
              "on-surface": "#d4e4fa",
              "on-secondary-fixed": "#111c2d",
              "surface-variant": "#273647"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "lg": "40px",
              "gutter": "24px",
              "margin": "32px",
              "base": "8px",
              "xs": "4px",
              "md": "24px",
              "sm": "12px",
              "xl": "64px"
      },
      "fontFamily": {
              "body-lg": ["Inter"],
              "label-md": ["Inter"],
              "h1": ["Inter"],
              "h3": ["Inter"],
              "body-md": ["Inter"],
              "label-sm": ["Inter"],
              "h2": ["Inter"]
      },
      "fontSize": {
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "h1": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "h3": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "h2": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
